### PR TITLE
add script to create source tarballs for EasyBuild releases

### PR DESCRIPTION
**Pull request by boegel**
This script was mainly created to make it easier to correctly create the source distribution for `easybuild-easyconfigs`, including the index file created with "`eb --create-index`" (see https://github.com/easybuilders/easybuild-framework/pull/3210 + https://github.com/easybuilders/easybuild/pull/611), but it's also useful for the other `easybuild*` repositories.

Example usage:

* framework:

```
$ cd ~/work/easybuild-framework
$ ~/work/easybuild/scripts/create_source_tarball.sh easybuild-framework 4.1.2.dev0
>> (start: Mon Apr 13 18:03:27 CEST 2020)
>> creating source tarball for easybuild-framework 4.1.2.dev0...
>> current working directory: /Users/kehoste/work/WIP/easybuild-framework ... OK
>> making sure dist/easybuild-framework-4.1.2.dev0.tar.gz doesn't exist yet ... OK
>> checking for clean working directory... OK
>> running 'python setup.py sdist'... OK
>> output of 'python setup.py sdist' in /tmp/tmp.BlakyTNJ/sdist.out
>> checking for dist/easybuild-framework-4.1.2.dev0.tar.gz ... OK
>> checking for unpacked source tarball at /tmp/tmp.BlakyTNJ/easybuild-framework-4.1.2.dev0 ... OK

SUCCESS!
Source tarball for easybuild-framework 4.1.2.dev0 is ready for publishing with:
    twine upload dist/easybuild-framework-4.1.2.dev0.tar.gz

>> (end: Mon Apr 13 18:03:30 CEST 2020)
```

* easyconfigs:

```
$ cd ~/work/easybuild-easyconfigs
$ ~/work/easybuild/scripts/create_source_tarball.sh easybuild-easyconfigs 4.1.2.dev0
>> (start: Mon Apr 13 17:30:15 CEST 2020)
>> creating source tarball for easybuild-easyconfigs 4.1.2.dev0...
>> checking whether 'eb' command is available ... OK
>> checking whether 'eb --create-index' is supported ... OK
>> current working directory: /Users/kehoste/work/WIP/easybuild-easyconfigs ... OK
>> making sure dist/easybuild-easyconfigs-4.1.2.dev0.tar.gz doesn't exist yet ... OK
>> checking for clean working directory... OK
>> creating index file with 'eb --create-index easybuild/easyconfigs --force'... OK
>> checking for easybuild/easyconfigs/.eb-path-index ... OK
>> running 'python setup.py sdist'... OK
>> output of 'python setup.py sdist' in /tmp/tmp.ZbKBqde9/sdist.out
>> checking for dist/easybuild-easyconfigs-4.1.2.dev0.tar.gz ... OK
>> checking for unpacked source tarball at /tmp/tmp.ZbKBqde9/easybuild-easyconfigs-4.1.2.dev0 ... OK
>> checking for /tmp/tmp.ZbKBqde9/easybuild-easyconfigs-4.1.2.dev0/easybuild/easyconfigs/.eb-path-index ... OK
>> checking whether all files are included in index ... 14437/14436 OK
>> checking whether all files in index actually exist in unpacked source tarball ... 14437/14436 OK
>> checking for CVS easyconfigs in source tarball... OK

SUCCESS!
Source tarball for easybuild-easyconfigs 4.1.2.dev0 is ready for publishing with:
    twine upload dist/easybuild-easyconfigs-4.1.2.dev0.tar.gz

>> (end: Mon Apr 13 17:34:21 CEST 2020)
```

### CODE REVIEW

**Comment by boegel** [comment]
@migueldiascosta It took a bit of effort to make the tests happy, but I think this is good to go now...

I've enhanced the `create_source_tarball.sh` script a bit after you used it for the EasyBuild v4.2.0 release, so it spits out warnings in case the version for the `easybuild` package are misaligned with the `easybuild-*` packages it specifies in `requires`  in `setup.py`.

For both EasyBuild v4.1.2 (due to the `4.1.1` version for easyblocks/easyconfigs) and EasyBuild v4.2.0 (due to `4.2.0.post0` vs `4.2.0`) the script produces clear warnings that the versioning looked a bit off, but it would still build the source distribution.

You should be able to run it on current `master` to get an idea of how that looks...

**Comment by migueldiascosta** [comment]
yes, works as advertised :)

**Comment by boegel** [comment]
@migueldiascosta So, good to merge then?

**Comment by migueldiascosta** [comment]
Going in, thanks @boegel!

**Pull request merged**
