### PR TITLE
Travis CI: Add Python 3.8 to the testing

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by boegel** [comment]
This requires the fix made in https://github.com/easybuilders/easybuild-framework/pull/3078, so tests will keep failing until next EasyBuild release is pushed to PyPI (which should happen early next week).

**Comment by cclauss** [comment]
Should we run Python 3.8 in __allow_failures__ mode temporarily until then so that Travis stays green?

**Comment by boegel** [comment]
@cclauss I don't see how that provides any extra value of just waiting a week to also run the tests with Python 3.8...

**Comment by migueldiascosta** [comment]
closing and reopening to trigger travis

**Comment by migueldiascosta** [comment]
Going in, thanks @cclauss!

**Pull request merged**
