### PR TITLE
create CODE_OF_CONDUCT

### LINKED ISSUE #566: missing code-of-conduct file
@boegel  missing code of conduct for easybuild. See https://opensource.guide/code-of-conduct/
There are several templates for ``CODE_OF_CONDUCT.md`` file. 

Here is one example: https://www.contributor-covenant.org/version/1/4/code-of-conduct.html 

I know this may be trivial for some of us, but definitely important for new users who want to contribute back. Consider adding this document and linking this to Contributing Guide file found in 
each repo
- https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/CONTRIBUTING.md
- https://github.com/easybuilders/easybuild-framework/blob/develop/CONTRIBUTING.md
- https://github.com/easybuilders/easybuild-easyblocks/blob/develop/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
fix #566
@boegel here is CODE_OF_CONDUCT file. Please confirm email ``easybuild@lists.ugent.be``

### CODE REVIEW

**Comment by boegel** [comment]
@shahzebsiddiqui Thank you very much for looking into this.

We should definitely add a CoC to the different EasyBuild repositories, but I'd like to take the time to 1) look into the different standard ones that are out there, 2) ask for input from the EasyBuild maintainers, 3) also announce this on the EasyBuild mailing list (and Slack channel).

Please give us some time for this, this is not something that should be rushed in...

**Comment by shahzebsiddiqui** [comment]
no worries @boegel. If you decide to go with **Contributor Covenant** then feel free to merge this. For more details on CoC see https://opensource.guide/code-of-conduct/

**Comment by shahzebsiddiqui** [comment]
The other CoC template is the following: http://citizencodeofconduct.org/

**Comment by shahzebsiddiqui** [comment]
@boegel I am closing this PR.
This is not relevant anymore

**Comment by boegel** [comment]
To be clear: having a code of conduct is still very relevant of course, but we haven't finalized that process yet.

I'll try to get back to that ASAP...

**Comment by shahzebsiddiqui** [comment]
I agree it is important, now i think about it doesn't make sense i send this PR it should be done by one of the eb maintainers.

**Pull request closed without merging**
